# Generated by Django 3.2.9 on 2021-11-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0002_pictures_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='name',
            field=models.CharField(default='Unnamed picture', max_length=50, verbose_name='Название фотографии'),
        ),
    ]
