# Generated by Django 3.2.9 on 2021-11-21 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymaps', '0003_pictures_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ('name',), 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'ordering': ('name',), 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='locations',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mymaps.cities', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mymaps.locations', verbose_name='Место'),
        ),
    ]
